-- Adventure Works FEA — challenge sales analyses (index)
-- These files are compiled by dbt but not run in `dbt build`.
-- Preview in Cloud / CLI, e.g.:
--   dbt show --select e_timeseries_month_year --limit 50
--   dbt show --select f_top_product_promotion --limit 1
--
-- Metrics (from fact_sales):
--   number of orders        = count(distinct sales_order_id)
--   quantity purchased      = sum(order_qty)
--   total transaction value = sum(net_line_total)
--   AOV                     = sum(net_line_total) / count(distinct sales_order_id)
--
-- | Q | File                              | Purpose                                      |
-- |---|-----------------------------------|----------------------------------------------|
-- | a | a_orders_qty_value_by_dims.sql    | Orders / qty / value by product, card,       |
-- |   |                                   | reason, date, customer, status, geo          |
-- | b | b_aov_by_product_geo_time.sql     | Highest AOV by product, month, year, geo     |
-- | c | c_top10_customers.sql             | Top 10 customers by transaction value        |
-- | d | d_top5_cities.sql                 | Top 5 cities by transaction value            |
-- | e | e_timeseries_month_year.sql       | Orders / qty / value by month & year         |
-- | f | f_top_product_promotion.sql       | Top product by units for reason Promotion    |
-- | — | debug_gross_sales_2011.sql        | CEO / accounting 2011 gross sales audit      |
--
-- Bridge rule: when filtering by reason without grouping by it, use EXISTS /
-- distinct order ids (c, d, f). When grouping by reason (a), join the bridge.

select 1 as analyses_index_placeholder
